<?xml version="1.0" encoding="utf-8"?><Database Name="ScrumNotesCombiner" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=O141;Initial Catalog=ScrumNotesCombiner;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ScrumNotesCombinerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.projects" Member="projects">
    <Type Name="project">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Allias" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ProjectAdminId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EstFinishDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ScrumAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScheduleStatus" Member="ScheduleStatus">
    <Type Name="ScheduleStatus">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Allias" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DayOfWeek" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DayOfMonth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ScheduledTime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="emails" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ScrumTemplateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScrumNotesTemplates" Member="ScrumNotesTemplates">
    <Type Name="ScrumNotesTemplate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SchedulingTemplateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="markup" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Allias" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ADusername" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="comments" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.UserStatuses" Member="UserStatuses">
    <Type Name="UserStatuse">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScheduleStatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Period1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Period2" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Blockers" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Function Name="dbo.check_role_existance" Method="check_role_existance">
    <Parameter Name="Role" Parameter="role" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="check_role_existanceResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.check_status_existance" Method="check_status_existance">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProjectID" Parameter="projectID" Type="System.Int32" DbType="Int" />
    <Parameter Name="count" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.check_user_existance" Method="check_user_existance">
    <Parameter Name="AdName" Parameter="adName" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="check_user_existanceResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.delete_project" Method="delete_project">
    <Parameter Name="project_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.delete_scrumtemplate" Method="delete_scrumtemplate">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.check_project_existance" Method="check_project_existance">
    <Parameter Name="allias" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="count" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>